[build]
  command = "npm start" # Start your server
  publish = "public"    # Change if you have a different directory for static files

[dev]
  functions = "netlify-functions" # Optional: if you're using Netlify functions
  port = 3000
