[build]
  command = "npm start"
  publish = "public"  # Replace with the directory containing your static files if needed

[dev]
  functions = "netlify-functions" # Optional: if using Netlify functions
  port = 3000
