[build]
  command = "npm start" # Start your server
  publish = "." # Publish the root directory if no static folder

[dev]
  functions = "netlify-functions" # Optional: if using Netlify functions
  port = 3000
